### ISSUE TITLE
Use Redis cluster

### ISSUE THREAD

**Issue by brnbs** [Elders/RedLock#9]
Thanks for creating this RedLock library! I noticed a PR [#1](https://github.com/Elders/RedLock/pull/1) suggesting multi-server support, but I can't find the option in the current code. Since the main idea behind the RedLock algorithm is to use multiple Redis servers, does the library support this feature? If so, how can it be configured?

**Comment by ethno2405** [comment]
@brnbs You should be able to specify multiple servers in the connection string separated by a comma. The connection string is passed to the Redis `ConnectionMultiplexer`.
